import type { BedrockClientBase } from "../main.ts";
import { LoginHandler } from "./not_used/login.ts";
import { PlayStatusHandler } from "./play_status.ts";
import { ServerToClientHandshakeHandler } from "./not_used/server_to_client_handshake.ts";
import { ClientToServerHandshakeHandler } from "./not_used/client_to_server_handshake.ts";
import { DisconnectHandler } from "./not_used/disconnect.ts";
import { ResourcePacksInfoHandler } from "./not_used/resource_packs_info.ts";
import { ResourcePackStackHandler } from "./not_used/resource_pack_stack.ts";
import { ResourcePackClientResponseHandler } from "./not_used/resource_pack_client_response.ts";
import { TextHandler } from "./not_used/text.ts";
import { SetTimeHandler } from "./not_used/set_time.ts";
import { StartGameHandler } from "./start_game.ts";
import { AddPlayerHandler } from "./add_player.ts";
import { AddEntityHandler } from "./add_entity.ts";
import { RemoveEntityHandler } from "./remove_entity.ts";
import { AddItemEntityHandler } from "./add_item_entity.ts";
import { TakeItemEntityHandler } from "./not_used/take_item_entity.ts";
import { MoveEntityHandler } from "./move_entity.ts";
import { MovePlayerHandler } from "./move_player.ts";
import { RiderJumpHandler } from "./not_used/rider_jump.ts";
import { UpdateBlockHandler } from "./update_block.ts";
import { AddPaintingHandler } from "./not_used/add_painting.ts";
import { TickSyncHandler } from "./not_used/tick_sync.ts";
import { LevelSoundEventOldHandler } from "./not_used/level_sound_event_old.ts";
import { LevelEventHandler } from "./not_used/level_event.ts";
import { BlockEventHandler } from "./not_used/block_event.ts";
import { EntityEventHandler } from "./entity_event.ts";
import { MobEffectHandler } from "./not_used/mob_effect.ts";
import { UpdateAttributesHandler } from "./update_attributes.ts";
import { InventoryTransactionHandler } from "./not_used/inventory_transaction.ts";
import { MobEquipmentHandler } from "./not_used/mob_equipment.ts";
import { MobArmorEquipmentHandler } from "./not_used/mob_armor_equipment.ts";
import { InteractHandler } from "./not_used/interact.ts";
import { BlockPickRequestHandler } from "./not_used/block_pick_request.ts";
import { EntityPickRequestHandler } from "./not_used/entity_pick_request.ts";
import { PlayerActionHandler } from "./not_used/player_action.ts";
import { HurtArmorHandler } from "./not_used/hurt_armor.ts";
import { SetEntityDataHandler } from "./set_entity_data.ts";
import { SetEntityMotionHandler } from "./set_entity_motion.ts";
import { SetEntityLinkHandler } from "./set_entity_link.ts";
import { SetHealthHandler } from "./not_used/set_health.ts";
import { SetSpawnPositionHandler } from "./not_used/set_spawn_position.ts";
import { AnimateHandler } from "./not_used/animate.ts";
import { RespawnHandler } from "./not_used/respawn.ts";
import { ContainerOpenHandler } from "./not_used/container_open.ts";
import { ContainerCloseHandler } from "./not_used/container_close.ts";
import { PlayerHotbarHandler } from "./not_used/player_hotbar.ts";
import { InventoryContentHandler } from "./not_used/inventory_content.ts";
import { InventorySlotHandler } from "./not_used/inventory_slot.ts";
import { ContainerSetDataHandler } from "./not_used/container_set_data.ts";
import { CraftingDataHandler } from "./not_used/crafting_data.ts";
import { CraftingEventHandler } from "./not_used/crafting_event.ts";
import { GuiDataPickItemHandler } from "./not_used/gui_data_pick_item.ts";
import { AdventureSettingsHandler } from "./not_used/adventure_settings.ts";
import { BlockEntityDataHandler } from "./not_used/block_entity_data.ts";
import { PlayerInputHandler } from "./not_used/player_input.ts";
import { LevelChunkHandler } from "./level_chunk.ts";
import { SetCommandsEnabledHandler } from "./not_used/set_commands_enabled.ts";
import { SetDifficultyHandler } from "./not_used/set_difficulty.ts";
import { ChangeDimensionHandler } from "./not_used/change_dimension.ts";
import { SetPlayerGameTypeHandler } from "./not_used/set_player_game_type.ts";
import { PlayerListHandler } from "./player_list.ts";
import { SimpleEventHandler } from "./not_used/simple_event.ts";
import { EventHandler } from "./not_used/event.ts";
import { SpawnExperienceOrbHandler } from "./not_used/spawn_experience_orb.ts";
import { ClientboundMapItemDataHandler } from "./not_used/clientbound_map_item_data.ts";
import { MapInfoRequestHandler } from "./not_used/map_info_request.ts";
import { RequestChunkRadiusHandler } from "./not_used/request_chunk_radius.ts";
import { ChunkRadiusUpdateHandler } from "./not_used/chunk_radius_update.ts";
import { GameRulesChangedHandler } from "./not_used/game_rules_changed.ts";
import { CameraHandler } from "./not_used/camera.ts";
import { BossEventHandler } from "./not_used/boss_event.ts";
import { ShowCreditsHandler } from "./not_used/show_credits.ts";
import { AvailableCommandsHandler } from "./not_used/available_commands.ts";
import { CommandRequestHandler } from "./not_used/command_request.ts";
import { CommandBlockUpdateHandler } from "./not_used/command_block_update.ts";
import { CommandOutputHandler } from "./not_used/command_output.ts";
import { UpdateTradeHandler } from "./not_used/update_trade.ts";
import { UpdateEquipmentHandler } from "./not_used/update_equipment.ts";
import { ResourcePackDataInfoHandler } from "./not_used/resource_pack_data_info.ts";
import { ResourcePackChunkDataHandler } from "./not_used/resource_pack_chunk_data.ts";
import { ResourcePackChunkRequestHandler } from "./not_used/resource_pack_chunk_request.ts";
import { TransferHandler } from "./not_used/transfer.ts";
import { PlaySoundHandler } from "./not_used/play_sound.ts";
import { StopSoundHandler } from "./not_used/stop_sound.ts";
import { SetTitleHandler } from "./not_used/set_title.ts";
import { AddBehaviorTreeHandler } from "./not_used/add_behavior_tree.ts";
import { StructureBlockUpdateHandler } from "./not_used/structure_block_update.ts";
import { ShowStoreOfferHandler } from "./not_used/show_store_offer.ts";
import { PurchaseReceiptHandler } from "./not_used/purchase_receipt.ts";
import { PlayerSkinHandler } from "./not_used/player_skin.ts";
import { SubClientLoginHandler } from "./not_used/sub_client_login.ts";
import { InitiateWebSocketConnectionHandler } from "./not_used/initiate_web_socket_connection.ts";
import { SetLastHurtByHandler } from "./not_used/set_last_hurt_by.ts";
import { BookEditHandler } from "./not_used/book_edit.ts";
import { NpcRequestHandler } from "./not_used/npc_request.ts";
import { PhotoTransferHandler } from "./not_used/photo_transfer.ts";
import { ModalFormRequestHandler } from "./not_used/modal_form_request.ts";
import { ModalFormResponseHandler } from "./not_used/modal_form_response.ts";
import { ServerSettingsRequestHandler } from "./not_used/server_settings_request.ts";
import { ServerSettingsResponseHandler } from "./not_used/server_settings_response.ts";
import { ShowProfileHandler } from "./not_used/show_profile.ts";
import { SetDefaultGameTypeHandler } from "./not_used/set_default_game_type.ts";
import { RemoveObjectiveHandler } from "./not_used/remove_objective.ts";
import { SetDisplayObjectiveHandler } from "./not_used/set_display_objective.ts";
import { SetScoreHandler } from "./not_used/set_score.ts";
import { LabTableHandler } from "./not_used/lab_table.ts";
import { UpdateBlockSyncedHandler } from "./not_used/update_block_synced.ts";
import { MoveEntityDeltaHandler } from "./move_entity_delta.ts";
import { SetScoreboardIdentityHandler } from "./not_used/set_scoreboard_identity.ts";
import { SetLocalPlayerAsInitializedHandler } from "./not_used/set_local_player_as_initialized.ts";
import { UpdateSoftEnumHandler } from "./not_used/update_soft_enum.ts";
import { NetworkStackLatencyHandler } from "./not_used/network_stack_latency.ts";
import { ScriptCustomEventHandler } from "./not_used/script_custom_event.ts";
import { SpawnParticleEffectHandler } from "./not_used/spawn_particle_effect.ts";
import { AvailableEntityIdentifiersHandler } from "./not_used/available_entity_identifiers.ts";
import { LevelSoundEventV2Handler } from "./not_used/level_sound_event_v2.ts";
import { NetworkChunkPublisherUpdateHandler } from "./not_used/network_chunk_publisher_update.ts";
import { BiomeDefinitionListHandler } from "./not_used/biome_definition_list.ts";
import { LevelSoundEventHandler } from "./not_used/level_sound_event.ts";
import { LevelEventGenericHandler } from "./not_used/level_event_generic.ts";
import { LecternUpdateHandler } from "./not_used/lectern_update.ts";
import { VideoStreamConnectHandler } from "./not_used/video_stream_connect.ts";
import { ClientCacheStatusHandler } from "./not_used/client_cache_status.ts";
import { OnScreenTextureAnimationHandler } from "./not_used/on_screen_texture_animation.ts";
import { MapCreateLockedCopyHandler } from "./not_used/map_create_locked_copy.ts";
import { StructureTemplateDataExportRequestHandler } from "./not_used/structure_template_data_export_request.ts";
import { StructureTemplateDataExportResponseHandler } from "./not_used/structure_template_data_export_response.ts";
import { UpdateBlockPropertiesHandler } from "./not_used/update_block_properties.ts";
import { ClientCacheBlobStatusHandler } from "./not_used/client_cache_blob_status.ts";
import { ClientCacheMissResponseHandler } from "./client_cache_miss_response.ts";
import { EducationSettingsHandler } from "./not_used/education_settings.ts";
import { EmoteHandler } from "./not_used/emote.ts";
import { MultiplayerSettingsHandler } from "./not_used/multiplayer_settings.ts";
import { SettingsCommandHandler } from "./not_used/settings_command.ts";
import { AnvilDamageHandler } from "./not_used/anvil_damage.ts";
import { CompletedUsingItemHandler } from "./not_used/completed_using_item.ts";
import { NetworkSettingsHandler } from "./not_used/network_settings.ts";
import { PlayerAuthInputHandler } from "./not_used/player_auth_input.ts";
import { CreativeContentHandler } from "./not_used/creative_content.ts";
import { PlayerEnchantOptionsHandler } from "./not_used/player_enchant_options.ts";
import { ItemStackRequestHandler } from "./not_used/item_stack_request.ts";
import { ItemStackResponseHandler } from "./not_used/item_stack_response.ts";
import { PlayerArmorDamageHandler } from "./not_used/player_armor_damage.ts";
import { CodeBuilderHandler } from "./not_used/code_builder.ts";
import { UpdatePlayerGameTypeHandler } from "./not_used/update_player_game_type.ts";
import { EmoteListHandler } from "./not_used/emote_list.ts";
import { PositionTrackingDbRequestHandler } from "./not_used/position_tracking_db_request.ts";
import { PositionTrackingDbBroadcastHandler } from "./not_used/position_tracking_db_broadcast.ts";
import { DebugInfoHandler } from "./not_used/debug_info.ts";
import { PacketViolationWarningHandler } from "./not_used/packet_violation_warning.ts";
import { MotionPredictionHintsHandler } from "./not_used/motion_prediction_hints.ts";
import { AnimateEntityHandler } from "./not_used/animate_entity.ts";
import { CameraShakeHandler } from "./not_used/camera_shake.ts";
import { PlayerFogHandler } from "./not_used/player_fog.ts";
import { CorrectPlayerMovePredictionHandler } from "./correct_player_move_prediction.ts";
import { ItemRegistryHandler } from "./item_registry.ts";
import { FilterTextPacketHandler } from "./not_used/filter_text_packet.ts";
import { DebugRendererHandler } from "./not_used/debug_renderer.ts";
import { SyncEntityPropertyHandler } from "./not_used/sync_entity_property.ts";
import { AddVolumeEntityHandler } from "./not_used/add_volume_entity.ts";
import { RemoveVolumeEntityHandler } from "./not_used/remove_volume_entity.ts";
import { SimulationTypeHandler } from "./not_used/simulation_type.ts";
import { NpcDialogueHandler } from "./not_used/npc_dialogue.ts";
import { EduUriResourcePacketHandler } from "./not_used/edu_uri_resource_packet.ts";
import { CreatePhotoHandler } from "./not_used/create_photo.ts";
import { UpdateSubchunkBlocksHandler } from "./not_used/update_subchunk_blocks.ts";
import { PhotoInfoRequestHandler } from "./not_used/photo_info_request.ts";
import { SubchunkHandler } from "./subchunk.ts";
import { SubchunkRequestHandler } from "./not_used/subchunk_request.ts";
import { ClientStartItemCooldownHandler } from "./not_used/client_start_item_cooldown.ts";
import { ScriptMessageHandler } from "./not_used/script_message.ts";
import { CodeBuilderSourceHandler } from "./not_used/code_builder_source.ts";
import { TickingAreasLoadStatusHandler } from "./not_used/ticking_areas_load_status.ts";
import { DimensionDataHandler } from "./not_used/dimension_data.ts";
import { AgentActionHandler } from "./not_used/agent_action.ts";
import { ChangeMobPropertyHandler } from "./not_used/change_mob_property.ts";
import { LessonProgressHandler } from "./not_used/lesson_progress.ts";
import { RequestAbilityHandler } from "./not_used/request_ability.ts";
import { RequestPermissionsHandler } from "./not_used/request_permissions.ts";
import { ToastRequestHandler } from "./not_used/toast_request.ts";
import { UpdateAbilitiesHandler } from "./not_used/update_abilities.ts";
import { UpdateAdventureSettingsHandler } from "./not_used/update_adventure_settings.ts";
import { DeathInfoHandler } from "./not_used/death_info.ts";
import { EditorNetworkHandler } from "./not_used/editor_network.ts";
import { FeatureRegistryHandler } from "./not_used/feature_registry.ts";
import { ServerStatsHandler } from "./not_used/server_stats.ts";
import { RequestNetworkSettingsHandler } from "./not_used/request_network_settings.ts";
import { GameTestRequestHandler } from "./not_used/game_test_request.ts";
import { GameTestResultsHandler } from "./not_used/game_test_results.ts";
import { UpdateClientInputLocksHandler } from "./not_used/update_client_input_locks.ts";
import { ClientCheatAbilityHandler } from "./not_used/client_cheat_ability.ts";
import { CameraPresetsHandler } from "./not_used/camera_presets.ts";
import { UnlockedRecipesHandler } from "./not_used/unlocked_recipes.ts";
import { CameraInstructionHandler } from "./not_used/camera_instruction.ts";
import { CompressedBiomeDefinitionsHandler } from "./not_used/compressed_biome_definitions.ts";
import { TrimDataHandler } from "./not_used/trim_data.ts";
import { OpenSignHandler } from "./not_used/open_sign.ts";
import { AgentAnimationHandler } from "./not_used/agent_animation.ts";
import { RefreshEntitlementsHandler } from "./not_used/refresh_entitlements.ts";
import { ToggleCrafterSlotRequestHandler } from "./not_used/toggle_crafter_slot_request.ts";
import { SetPlayerInventoryOptionsHandler } from "./not_used/set_player_inventory_options.ts";
import { SetHudHandler } from "./not_used/set_hud.ts";
import { AwardAchievementHandler } from "./not_used/award_achievement.ts";
import { ServerPostMoveHandler } from "./not_used/server_post_move.ts";
import { ClientboundCloseFormHandler } from "./not_used/clientbound_close_form.ts";
import { ServerboundLoadingScreenHandler } from "./not_used/serverbound_loading_screen.ts";
import { JigsawStructureDataHandler } from "./not_used/jigsaw_structure_data.ts";
import { CurrentStructureFeatureHandler } from "./not_used/current_structure_feature.ts";
import { ServerboundDiagnosticsHandler } from "./not_used/serverbound_diagnostics.ts";
import { CameraAimAssistHandler } from "./not_used/camera_aim_assist.ts";
import { ContainerRegistryCleanupHandler } from "./not_used/container_registry_cleanup.ts";
import { MovementEffectHandler } from "./not_used/movement_effect.ts";
import { SetMovementAuthorityHandler } from "./not_used/set_movement_authority.ts";
import { CameraAimAssistPresetsHandler } from "./not_used/camera_aim_assist_presets.ts";
import { ClientCameraAimAssistHandler } from "./not_used/client_camera_aim_assist.ts";
import { ClientMovementPredictionSyncHandler } from "./not_used/client_movement_prediction_sync.ts";
import { UpdateClientOptionsHandler } from "./not_used/update_client_options.ts";
import { PlayerVideoCaptureHandler } from "./not_used/player_video_capture.ts";
import { PlayerUpdateEntityOverridesHandler } from "./not_used/player_update_entity_overrides.ts";
import { PlayerLocationHandler } from "./not_used/player_location.ts";
import { ClientboundControlsSchemeHandler } from "./not_used/clientbound_controls_scheme.ts";
import { ServerScriptDebugDrawerHandler } from "./not_used/server_script_debug_drawer.ts";
import { ServerboundPackSettingChangeHandler } from "./not_used/serverbound_pack_setting_change.ts";

export function registerAllHandlers(client: BedrockClientBase) {
  LoginHandler.register(client);
  PlayStatusHandler.register(client);
  ServerToClientHandshakeHandler.register(client);
  ClientToServerHandshakeHandler.register(client);
  DisconnectHandler.register(client);
  ResourcePacksInfoHandler.register(client);
  ResourcePackStackHandler.register(client);
  ResourcePackClientResponseHandler.register(client);
  TextHandler.register(client);
  SetTimeHandler.register(client);
  StartGameHandler.register(client);
  AddPlayerHandler.register(client);
  AddEntityHandler.register(client);
  RemoveEntityHandler.register(client);
  AddItemEntityHandler.register(client);
  TakeItemEntityHandler.register(client);
  MoveEntityHandler.register(client);
  MovePlayerHandler.register(client);
  RiderJumpHandler.register(client);
  UpdateBlockHandler.register(client);
  AddPaintingHandler.register(client);
  TickSyncHandler.register(client);
  LevelSoundEventOldHandler.register(client);
  LevelEventHandler.register(client);
  BlockEventHandler.register(client);
  EntityEventHandler.register(client);
  MobEffectHandler.register(client);
  UpdateAttributesHandler.register(client);
  InventoryTransactionHandler.register(client);
  MobEquipmentHandler.register(client);
  MobArmorEquipmentHandler.register(client);
  InteractHandler.register(client);
  BlockPickRequestHandler.register(client);
  EntityPickRequestHandler.register(client);
  PlayerActionHandler.register(client);
  HurtArmorHandler.register(client);
  SetEntityDataHandler.register(client);
  SetEntityMotionHandler.register(client);
  SetEntityLinkHandler.register(client);
  SetHealthHandler.register(client);
  SetSpawnPositionHandler.register(client);
  AnimateHandler.register(client);
  RespawnHandler.register(client);
  ContainerOpenHandler.register(client);
  ContainerCloseHandler.register(client);
  PlayerHotbarHandler.register(client);
  InventoryContentHandler.register(client);
  InventorySlotHandler.register(client);
  ContainerSetDataHandler.register(client);
  CraftingDataHandler.register(client);
  CraftingEventHandler.register(client);
  GuiDataPickItemHandler.register(client);
  AdventureSettingsHandler.register(client);
  BlockEntityDataHandler.register(client);
  PlayerInputHandler.register(client);
  LevelChunkHandler.register(client);
  SetCommandsEnabledHandler.register(client);
  SetDifficultyHandler.register(client);
  ChangeDimensionHandler.register(client);
  SetPlayerGameTypeHandler.register(client);
  PlayerListHandler.register(client);
  SimpleEventHandler.register(client);
  EventHandler.register(client);
  SpawnExperienceOrbHandler.register(client);
  ClientboundMapItemDataHandler.register(client);
  MapInfoRequestHandler.register(client);
  RequestChunkRadiusHandler.register(client);
  ChunkRadiusUpdateHandler.register(client);
  GameRulesChangedHandler.register(client);
  CameraHandler.register(client);
  BossEventHandler.register(client);
  ShowCreditsHandler.register(client);
  AvailableCommandsHandler.register(client);
  CommandRequestHandler.register(client);
  CommandBlockUpdateHandler.register(client);
  CommandOutputHandler.register(client);
  UpdateTradeHandler.register(client);
  UpdateEquipmentHandler.register(client);
  ResourcePackDataInfoHandler.register(client);
  ResourcePackChunkDataHandler.register(client);
  ResourcePackChunkRequestHandler.register(client);
  TransferHandler.register(client);
  PlaySoundHandler.register(client);
  StopSoundHandler.register(client);
  SetTitleHandler.register(client);
  AddBehaviorTreeHandler.register(client);
  StructureBlockUpdateHandler.register(client);
  ShowStoreOfferHandler.register(client);
  PurchaseReceiptHandler.register(client);
  PlayerSkinHandler.register(client);
  SubClientLoginHandler.register(client);
  InitiateWebSocketConnectionHandler.register(client);
  SetLastHurtByHandler.register(client);
  BookEditHandler.register(client);
  NpcRequestHandler.register(client);
  PhotoTransferHandler.register(client);
  ModalFormRequestHandler.register(client);
  ModalFormResponseHandler.register(client);
  ServerSettingsRequestHandler.register(client);
  ServerSettingsResponseHandler.register(client);
  ShowProfileHandler.register(client);
  SetDefaultGameTypeHandler.register(client);
  RemoveObjectiveHandler.register(client);
  SetDisplayObjectiveHandler.register(client);
  SetScoreHandler.register(client);
  LabTableHandler.register(client);
  UpdateBlockSyncedHandler.register(client);
  MoveEntityDeltaHandler.register(client);
  SetScoreboardIdentityHandler.register(client);
  SetLocalPlayerAsInitializedHandler.register(client);
  UpdateSoftEnumHandler.register(client);
  NetworkStackLatencyHandler.register(client);
  ScriptCustomEventHandler.register(client);
  SpawnParticleEffectHandler.register(client);
  AvailableEntityIdentifiersHandler.register(client);
  LevelSoundEventV2Handler.register(client);
  NetworkChunkPublisherUpdateHandler.register(client);
  BiomeDefinitionListHandler.register(client);
  LevelSoundEventHandler.register(client);
  LevelEventGenericHandler.register(client);
  LecternUpdateHandler.register(client);
  VideoStreamConnectHandler.register(client);
  ClientCacheStatusHandler.register(client);
  OnScreenTextureAnimationHandler.register(client);
  MapCreateLockedCopyHandler.register(client);
  StructureTemplateDataExportRequestHandler.register(client);
  StructureTemplateDataExportResponseHandler.register(client);
  UpdateBlockPropertiesHandler.register(client);
  ClientCacheBlobStatusHandler.register(client);
  ClientCacheMissResponseHandler.register(client);
  EducationSettingsHandler.register(client);
  EmoteHandler.register(client);
  MultiplayerSettingsHandler.register(client);
  SettingsCommandHandler.register(client);
  AnvilDamageHandler.register(client);
  CompletedUsingItemHandler.register(client);
  NetworkSettingsHandler.register(client);
  PlayerAuthInputHandler.register(client);
  CreativeContentHandler.register(client);
  PlayerEnchantOptionsHandler.register(client);
  ItemStackRequestHandler.register(client);
  ItemStackResponseHandler.register(client);
  PlayerArmorDamageHandler.register(client);
  CodeBuilderHandler.register(client);
  UpdatePlayerGameTypeHandler.register(client);
  EmoteListHandler.register(client);
  PositionTrackingDbRequestHandler.register(client);
  PositionTrackingDbBroadcastHandler.register(client);
  DebugInfoHandler.register(client);
  PacketViolationWarningHandler.register(client);
  MotionPredictionHintsHandler.register(client);
  AnimateEntityHandler.register(client);
  CameraShakeHandler.register(client);
  PlayerFogHandler.register(client);
  CorrectPlayerMovePredictionHandler.register(client);
  ItemRegistryHandler.register(client);
  FilterTextPacketHandler.register(client);
  DebugRendererHandler.register(client);
  SyncEntityPropertyHandler.register(client);
  AddVolumeEntityHandler.register(client);
  RemoveVolumeEntityHandler.register(client);
  SimulationTypeHandler.register(client);
  NpcDialogueHandler.register(client);
  EduUriResourcePacketHandler.register(client);
  CreatePhotoHandler.register(client);
  UpdateSubchunkBlocksHandler.register(client);
  PhotoInfoRequestHandler.register(client);
  SubchunkHandler.register(client);
  SubchunkRequestHandler.register(client);
  ClientStartItemCooldownHandler.register(client);
  ScriptMessageHandler.register(client);
  CodeBuilderSourceHandler.register(client);
  TickingAreasLoadStatusHandler.register(client);
  DimensionDataHandler.register(client);
  AgentActionHandler.register(client);
  ChangeMobPropertyHandler.register(client);
  LessonProgressHandler.register(client);
  RequestAbilityHandler.register(client);
  RequestPermissionsHandler.register(client);
  ToastRequestHandler.register(client);
  UpdateAbilitiesHandler.register(client);
  UpdateAdventureSettingsHandler.register(client);
  DeathInfoHandler.register(client);
  EditorNetworkHandler.register(client);
  FeatureRegistryHandler.register(client);
  ServerStatsHandler.register(client);
  RequestNetworkSettingsHandler.register(client);
  GameTestRequestHandler.register(client);
  GameTestResultsHandler.register(client);
  UpdateClientInputLocksHandler.register(client);
  ClientCheatAbilityHandler.register(client);
  CameraPresetsHandler.register(client);
  UnlockedRecipesHandler.register(client);
  CameraInstructionHandler.register(client);
  CompressedBiomeDefinitionsHandler.register(client);
  TrimDataHandler.register(client);
  OpenSignHandler.register(client);
  AgentAnimationHandler.register(client);
  RefreshEntitlementsHandler.register(client);
  ToggleCrafterSlotRequestHandler.register(client);
  SetPlayerInventoryOptionsHandler.register(client);
  SetHudHandler.register(client);
  AwardAchievementHandler.register(client);
  ServerPostMoveHandler.register(client);
  ClientboundCloseFormHandler.register(client);
  ServerboundLoadingScreenHandler.register(client);
  JigsawStructureDataHandler.register(client);
  CurrentStructureFeatureHandler.register(client);
  ServerboundDiagnosticsHandler.register(client);
  CameraAimAssistHandler.register(client);
  ContainerRegistryCleanupHandler.register(client);
  MovementEffectHandler.register(client);
  SetMovementAuthorityHandler.register(client);
  CameraAimAssistPresetsHandler.register(client);
  ClientCameraAimAssistHandler.register(client);
  ClientMovementPredictionSyncHandler.register(client);
  UpdateClientOptionsHandler.register(client);
  PlayerVideoCaptureHandler.register(client);
  PlayerUpdateEntityOverridesHandler.register(client);
  PlayerLocationHandler.register(client);
  ClientboundControlsSchemeHandler.register(client);
  ServerScriptDebugDrawerHandler.register(client);
  ServerboundPackSettingChangeHandler.register(client);
}
